### ISSUE TITLE
Dúvida de exercício

### ISSUE THREAD

**Issue by gegen07** [COLTEC-Android/E02-Activity#1]
"Você deverá entregar, junto do aplicativo, dois arquivos texto contendo o registro de log para as duas situações: (a) login feito corretamente; e (b) Login feito incorretamente."
Precisa fazer os arquivos texto ou só usar o Log.e (por exemplo) para registrar o log no logcat? Se for necessário os arquivos textos seriam armazenados no celular/emulador, ou um arquivo texto que seria adicionado ao projeto?

**Comment by jemaf** [comment]
Olá Germano,

Nesse caso o ideal seria você copiar as mensagens do logcat para um arquivo texto (nas duas situações).
